### ISSUE TITLE
"Advanced Usage" section is missing

### ISSUE THREAD

**Issue by kenjis** [auraphp/Aura.Filter#55] opened 2014-08-10 21:34 UTC
README.md says

> (Note that if we instantiate it manually, we will need to configure the RuleLocator manually to add rule services. See the "Advanced Usage" section near the end of this page for more information.)

But there is no "Advanced Usage" section in README.

**Comment by harikt** [comment] 2014-08-11 02:27
Duplicate of #32

**Comment by pmjones** [comment] 2015-07-03 17:05
I have just addressed this in the 2.x branch: https://github.com/auraphp/Aura.Filter/blob/2.x/docs/custom.md#set-a-factory-in-the-locator

**Closed as completed by pmjones** 2015-07-03 17:05 UTC
Labels: duplicate, enhancement, todo
